# Generated by Django 6.0.3 on 2026-05-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_db_connection', '0005_contactinfo_message_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='AboutStat',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='DashboardSettings',
        ),
        migrations.DeleteModel(
            name='db_home',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
